/**
 * Mock API-Football /fixtures endpoint
 *
 * The cron sync fetches:
 *   GET /fixtures?league=1&season=2026&status=FT-AET-PEN-1H-...
 *
 * This mock reads scripts/mock-base-fixtures.json (generated by seed-test.mjs)
 * and overlays results from scripts/mock-state.json (set via /set-result).
 * Only available in development.
 */

import { NextRequest, NextResponse } from 'next/server'
import { readFileSync, existsSync } from 'fs'
import path from 'path'

if (process.env.NODE_ENV === 'production') {
  throw new Error('Mock API must not be used in production')
}

const BASE_PATH  = path.join(process.cwd(), 'scripts', 'mock-base-fixtures.json')
const STATE_PATH = path.join(process.cwd(), 'scripts', 'mock-state.json')

interface BaseFixture {
  fixture: {
    id:     number
    date:   string
    status: { short: string; long: string; elapsed: number | null }
  }
  league:  { id: number; name: string; season: number; round: string }
  teams:   {
    home: { id: number; name: string; logo: null; winner: boolean | null }
    away: { id: number; name: string; logo: null; winner: boolean | null }
  }
  goals:  { home: number | null; away: number | null }
  score:  { fulltime: { home: number | null; away: number | null } }
  _match_id: number
}

interface MatchResult {
  status:  string
  home:    number
  away:    number
}

export async function GET(request: NextRequest) {
  if (!existsSync(BASE_PATH)) {
    return NextResponse.json(
      { error: 'mock-base-fixtures.json not found. Run: node --env-file=.env.local scripts/seed-test.mjs' },
      { status: 503 },
    )
  }

  const statusFilter = request.nextUrl.searchParams.get('status') ?? ''
  const requestedStatuses = new Set(statusFilter.split('-').filter(Boolean))

  const { response: baseFixtures }: { response: BaseFixture[] } =
    JSON.parse(readFileSync(BASE_PATH, 'utf8'))

  const state: { results: Record<string, MatchResult> } = existsSync(STATE_PATH)
    ? JSON.parse(readFileSync(STATE_PATH, 'utf8'))
    : { results: {} }

  // Merge base fixtures with state overrides
  const merged = baseFixtures.map((f) => {
    const override = state.results[String(f.fixture.id)]
    if (!override) return f

    const isHome = override.home > override.away
    const isAway = override.away > override.home

    return {
      ...f,
      fixture: {
        ...f.fixture,
        status: { short: override.status, long: override.status, elapsed: 90 },
      },
      teams: {
        home: { ...f.teams.home, winner: isHome ? true  : isAway ? false : false },
        away: { ...f.teams.away, winner: isAway ? true  : isHome ? false : false },
      },
      goals: { home: override.home, away: override.away },
      score: { fulltime: { home: override.home, away: override.away } },
    }
  })

  // Filter by the status codes requested by the cron
  const filtered = requestedStatuses.size > 0
    ? merged.filter(f => requestedStatuses.has(f.fixture.status.short))
    : merged

  return NextResponse.json({
    get:        'fixtures',
    parameters: Object.fromEntries(request.nextUrl.searchParams),
    results:    filtered.length,
    response:   filtered,
  })
}
